config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'admin/home#index'

  resources :passwords, except: %i[show] do
    collection do
      get :unrecognised
      get :updated
    end
  end

  scope module: :admin, path: :admin do
    root to: 'home#index', as: :admin_root

    # Camp Management
    resources :camp_locations do
      resources :children, only: %i[index]
      resources :seasons, except: %i[show]
    end

    resources :welcome_videos, except: %i[show]

    resources :seasons, only: [] do
      resources :camps, except: %i[show]
    end

    resources :camps, only: [] do
      resources :attendances, module: :camps
      resources :cabins
      resources :media_items, except: %i[show]

      resources :imports, module: :camps, only: %i[new create show] do
        get :template_csv, on: :collection
      end
    end

    # Admin Settings
    resources :admins, except: %i[show]

    resources :children, except: %i[show]

    resources :color_themes, except: %i[show]

    resources :conversations, only: %i[index show]

    namespace :users do
      resources :sessions, only: %i[create destroy]
      resource :merge, only: %i[new create]
    end

    # Content Management
    resources :camper_questions, except: %i[new create show]

    scope ':event_type', constraints: { event_type: /national|camp|cabin/ }, defaults: { event_type: 'national' } do
      resources :events, except: %i[show] do
        member do
          put :start
          put :open
          put :stop
        end

        resources :push_notifications, module: :events, only: %i[new create]
      end
    end

    resources :media_items, except: %i[show]

    resources :themes

    resources :quiz_questions, only: %i[edit update destroy]

    resources :settings, only: %i[index edit update]

    resources :streams, except: %i[show] do
      member do
        put :stop
      end
    end

    resources :tenants, except: %i[show] do
      get :switch, on: :member
      get :reset, on: :collection
    end

    resources :users, only: %i[] do
      resources :attendances, module: :users, only: %i[index destroy]
      resources :scores, module: :users, only: %i[index]
    end

    resources :comet_chat_reviews
  end

  namespace :api do
    namespace :v1 do
      resource :version, controller: :version

      namespace :users do
        resource :sessions, only: %i[show destroy]
      end
    end

    namespace :v2 do
      # Camp Endpoints
      resources :attendances, param: :code, only: %i[show create]
      resources :camp_locations, only: %i[] do
        resources :camps, only: %i[index]
      end

      # Content Endpoints
      resource :contact, only: %i[create]
      resources :camper_questions, only: %i[index create] do
        get :unread, on: :collection
      end
      resources :events, only: %i[index show]
      resources :media_items, only: %i[index]
      resources :themes, only: %i[index] do
        resources :quiz_questions, only: %i[index]
      end
      resources :scores, only: %i[index create]

      # User Management Endpoints
      resource :user, only: %i[show update]

      namespace :admin do
        resources :groups, only: %i[create]
        resources :camps, only: %i[show] do
          resources :cabins, only: %i[index]
        end

        resources :events, only: %i[create update destroy] do
          resources :push_notifications, module: :events, only: %i[create]
        end

        resources :seasons, only: %i[index]
        resources :streams, only: %i[index]
      end

      namespace :authentications do
        resource :sessions, only: %i[create show destroy]
        resources :passwords, param: :reset_token, only: %i[create show update]
      end

      resources :authentications, only: %i[create] do
        collection do
          get :check_username
        end
      end

      resources :users, param: :chat_uid, only: [] do
        resources :messages, only: %i[destroy]
      end

      namespace :users do
        resource :device_token, only: %i[create]
        resources :conversations, only: %i[index]
        resources :reachable_users, only: %i[index]
      end

      resources :settings, only: :index
    end
  end

  # Nice login/logout routes
  get 'login'    => 'admin/users/sessions#new',      as: :login
  get 'logout'   => 'admin/users/sessions#destroy',  as: :logout
end

app/models/camp.rb
# frozen_string_literal: true

class Camp < ApplicationRecord
  include Attendances
  include WelcomeVideoOrAttached

  attr_accessor :skip_chat_attribute_validation

  belongs_to :season

  has_one :camp_location, through: :season

  has_many :users, through: :attendances, dependent: :restrict_with_error
  has_many :admins, through: :attendances, class_name: 'User::Admin', source: :user
  has_many :children, through: :attendances, class_name: 'User::Child', source: :user
  has_many :cabins, dependent: :destroy
  has_many :imports, as: :scope
  has_many :media_items, class_name: 'MediaItem::CampMediaItem', dependent: :restrict_with_error

  has_many :targets, class_name: 'Event::Target', as: :target, dependent: :destroy
  has_many :events, through: :targets

  validates :name, presence: true
  validates :chat_guid, presence: true, unless: :skip_chat_attribute_validation

  def can_be_deleted?
    users.empty? && media_items.empty?
  end
end

app/models/event/cabin_event.rb
# frozen_string_literal: true

class Event::CabinEvent < Event
  has_many :cabins, through: :targets, source: :target, source_type: 'Cabin'

  validates :cabin_ids, length: { minimum: 1 }
end

app/models/event/camp_event.rb
# frozen_string_literal: true

class Event::CampEvent < Event
  has_many :camps, through: :targets, source: :target, source_type: 'Camp'

  validates :camp_ids, length: { minimum: 1 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include Attendances
  include CometchatCredentials
  include TenantResource

  enum gender: { female: 'female', male: 'male' }

  belongs_to :authentication, optional: true
  belongs_to :device_token, optional: true

  has_many :cabins, through: :attendances
  has_many :camps, through: :attendances
  has_many :camp_locations, through: :camps
  has_many :seasons, through: :camps
  has_many :contact_email_messages, dependent: :nullify
  has_many :media_items, dependent: :restrict_with_error
  has_many :scores, dependent: :destroy
  has_many :theme_scores, -> { where(scope_type: 'Theme') }, class_name: 'Score',
                                                             dependent: :nullify,
                                                             inverse_of: :user

  scope :registered, -> { where.not(authentication_id: nil) }
  scope :with_push_notifications, -> { where.not(device_token_id: nil) }

  accepts_nested_attributes_for :attendances, reject_if: :all_blank, allow_destroy: true

  after_destroy :cleanup_authentication

  validates :first_name, :last_name, :gender, presence: true
  validates :email, presence: true, email: true
  validate :validate_max_users, on: :create

  def admin?
    is_a?(User::Admin)
  end

  def child?
    is_a?(User::Child)
  end

  def registered? options={}
    authentication.present?
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def accessed!
    touch(:last_active_at)

    self
  end

  private

  def validate_max_users
    errors.add(:base, :too_many) if tenant && (tenant.users.count + 1 > tenant.max_users)
  end

  def cleanup_authentication
    authentication.destroy if authentication&.users&.none?
  end
end

app/controllers/admin/events/push_notifications_controller.rb
# frozen_string_literal: true

module Admin
  module Events
    class PushNotificationsController < ApplicationController
      def new
        @event = fetch_event
        decorated_event = EventDecorator.decorate(@event)

        authorize! :notify, @event

        @push_notification = Event::PushNotification.new(event: @event,
                                                         body: decorated_event.push_notification_body,
                                                         title: decorated_event.push_notification_title)
      end

      def create
        @event = fetch_event

        authorize! :notify, @event

        @push_notification = Event::PushNotification.new(allowed_params)
        @push_notification.event = @event

        if @push_notification.valid?
          @push_notification.deliver!

          redirect_to events_path(event_type: params[:event_type], past: @event.finished?), flash: { notice: t('flash.event.notified') }
        else
          render :new
        end
      end

      private

      def fetch_event
        @fetch_event ||= Event.find(params[:event_id])
      end

      def allowed_params
        params.require(:event_push_notification).permit(:body, :title)
      end
    end
  end
end

app/controllers/admin/events_controller.rb
# frozen_string_literal: true

module Admin
  class EventsController < ApplicationController
    def index
      authorize! :index, klass

      @showing_past = params[:past] == 'true'

      @events = klass.accessible_by(current_ability, :index)
      @events = @showing_past ? @events.finished.order(starts_at: :desc) : @events.present.order(active: :desc, starts_at: :asc, name: :asc)

      @events = @events.includes(:admin, :stream, :targets)
                       .page(params[:page])

      @new_event = klass.new(tenant_params)
      @tenant = TenantDecorator.decorate(current_tenant)
    end

    def new
      @event = klass.new(tenant_params)

      authorize! :new, @event

      # INFO: Set some sensible defaults, iOS has issues with blank datetime fields
      @event.starts_at = Time.now.beginning_of_hour + 1.hour
      @event.ends_at = @event.starts_at + 1.hour
    end

    def create
      @event = klass.new(allowed_params_with_tenant)
      @event.admin = current_user

      authorize! :create, @event

      event_creator = Interactions::Events::Creation.new(@event)

      if event_creator.execute
        redirect_to redirect_path, flash: { notice: t('flash.actions.create.notice', resource_name: resource_name) }
      else
        render :new
      end
    end

    def edit
      @event = fetch_event

      authorize! :update, @event
    end

    def update
      @event = fetch_event

      authorize! :update, @event

      if @event.update(allowed_params_with_tenant)
        redirect_to redirect_path, flash: { notice: t('flash.actions.update.notice', resource_name: resource_name) }
      else
        render :edit
      end
    end

    def destroy
      @event = fetch_event

      authorize! :destroy, @event

      if @event.closed? && @event.destroy
        flash[:notice] = t('flash.actions.destroy.notice', resource_name: resource_name)
      else
        flash[:error] = t('flash.actions.destroy.error', resource_name: resource_name)
      end

      redirect_to redirect_path
    end

    def start
      @event = fetch_event

      authorize! :start, @event

      if @event.start!
        flash[:notice] = t('flash.event.started')
      else
        flash[:error] = @event.errors.full_messages.to_sentence
      end

      redirect_to redirect_path
    end

    def open
      @event = fetch_event

      authorize! :open, @event

      @event.open!

      redirect_to redirect_path, flash: { notice: t('flash.event.opened') }
    end

    def stop
      @event = fetch_event

      authorize! :stop, @event

      @event.stop!

      redirect_to redirect_path, flash: { notice: t('flash.event.stopped') }
    end

    private

    def allowed_params
      params.require(:event).permit(:active,
                                    :description,
                                    :ends_at,
                                    :name,
                                    :starts_at,
                                    :thumbnail,
                                    camp_ids: [],
                                    cabin_ids: [])
    end

    def fetch_event
      @fetch_event = klass.find(params[:id])
    end

    def redirect_path
      events_path(event_type: params[:event_type], past: @event.finished?)
    end

    def klass
      case params[:event_type]
      when 'national'
        Event::NationalEvent
      when 'camp'
        Event::CampEvent
      when 'cabin'
        Event::CabinEvent
      end
    end

    def resource_name
      model_name(@event.class)
    end
  end
end

app/controllers/api/v2/admin/events/push_notifications_controller.rb
# frozen_string_literal: true

module API
  module V2
    module Admin
      module Events
        class PushNotificationsController < BaseController
          # == [POST] /api/v2/admin/events/{event_id}/push_notifications.json
          # Send a push notification regarding an event
          # ==== Returns
          # * 200 - success
          # * 422 - failure
          def create
            event = fetch_event
            decorated_event = EventDecorator.decorate(event)

            authorize! :notify, event

            push_notification = ::Event::PushNotification.new(event: event,
                                                              body: decorated_event.push_notification_body,
                                                              title: decorated_event.push_notification_title)

            if push_notification.valid?
              push_notification.deliver!

              render json: API::V2::Event::PushNotificationSerializer.new(push_notification, serializer_params)
            else
              render_object_error object: push_notification, serializer: API::V2::Event::PushNotificationSerializer, status: :unprocessable_entity
            end
          end

          private

          def fetch_event
            @fetch_event ||= ::Event.find(params[:event_id])
          end
        end
      end
    end
  end
end

app/controllers/api/v2/admin/events_controller.rb
# frozen_string_literal: true

module API
  module V2
    module Admin
      class EventsController < BaseController
        # == [POST] /api/v2/admin/events.json
        # Create an event
        # ==== Required
        # * active - active state of event (to show in app)
        # * description - event description
        # * ends_at - event end time
        # * name - event name
        # * starts_at - event start time
        # * camp_ids - camps involved in the event
        # * cabin_ids - cabins involved in the event
        # * event_type - event type
        def create
          event = klass.new(allowed_params_with_tenant.except(:event_type))
          authorize! :create, event

          event.admin = current_user
          event_creator = Interactions::Events::Creation.new(event)

          if event_creator.execute
            render json: API::V2::EventSerializer.new(event, serializer_params), status: :created
          else
            render_object_error object: event, serializer: API::V2::EventSerializer, status: :unprocessable_entity
          end
        end

        # == [PATCH] /api/v2/admin/events/:id.json
        # Update an event
        # ==== Optional
        # * active - active state of event (to show in app)
        # * description - event description
        # * ends_at - event end time
        # * name - event name
        # * starts_at - event start time
        # * camp_ids - camps involved in the event
        # * cabin_ids - cabins involved in the event
        # * event_type - event type
        # * action - action to do on the event
        def update
          event = klass.find_by!(id: params[:id])
          authorize! :update, event

          if %w[start open stop].include? allowed_params[:action]
            authorize! allowed_params[:action].to_sym, event

            if event.send("#{allowed_params[:action]}!")
              render json: API::V2::EventSerializer.new(event, serializer_params)
            else
              head :conflict
            end

          elsif event.update(allowed_params.except(:event_type))
            render json: API::V2::EventSerializer.new(event, serializer_params)
          else
            render_object_error object: event, serializer: API::V2::EventSerializer, status: :unprocessable_entity
          end
        end

        # == [DESTROY] /api/v2/admin/events/:id.json
        # destroy an event
        # ==== Required
        # * id - event to destroy (Implied in URL)
        def destroy
          event = ::Event.find_by!(id: params[:id])
          authorize! :destroy, event

          if !event.closed?
            head :conflict
          elsif event.destroy
            head :no_content
          else
            render_object_error object: event, serializer: API::V2::EventSerializer, status: :unprocessable_entity
          end
        end

        private

        def allowed_params
          params.from_jsonapi.require(:event).permit(:active,
                                                     :description,
                                                     :ends_at,
                                                     :name,
                                                     :starts_at,
                                                     :thumbnail,
                                                     :event_type,
                                                     :action,
                                                     camp_ids: [],
                                                     cabin_ids: [])
        end

        def klass
          case allowed_params[:event_type]
          when 'national'
            ::Event::NationalEvent
          when 'camp'
            ::Event::CampEvent
          when 'cabin'
            ::Event::CabinEvent
          else
            ::Event
          end
        end

        def serializer_params
          super.deep_merge(params: { include_url: true })
        end
      end
    end
  end
end

app/views/admin/events/_cabin.html.haml
- event.cabins.each do |cabin|
  %ul.list-unstyled.mb-0
    %li
      %strong= "#{model_name(CampLocation)}:"
      = cabin.camp.season.camp_location.name

    %li
      %strong= "#{model_name(Season)}:"
      = cabin.camp.season.name

    %li
      %strong= "#{model_name(Camp)}:"
      = cabin.camp.name

    %li
      %strong= "#{model_name(Cabin)}:"
      = cabin.name

app/views/admin/events/_camp.html.haml
- event.camps.each do |camp|
  %ul.list-unstyled.mb-0
    %li
      %strong= "#{model_name(CampLocation)}:"
      = camp.season.camp_location.name

    %li
      %strong= "#{model_name(Season)}:"
      = camp.season.name

    %li
      %strong= "#{model_name(Camp)}:"
      = camp.name

app/views/admin/events/_form.html.haml
= event_form.text_field :name
= event_form.text_area :description

- help_text = t('help.datetime_field', link: edit_admin_path(current_user), zone: Time.zone).html_safe


- if browser.safari?("< 14")
  = event_form.datetime_select :starts_at, help: help_text
  = event_form.datetime_select :ends_at, help: help_text
- else
  = event_form.form_group help: 'Syncs the start and end dates when editing either field' do
    = event_form.check_box :sync_dates, checked: true

  = event_form.datetime_field :starts_at, help: help_text
  = event_form.datetime_field :ends_at, help: help_text

= attachment_file_field event_form, :thumbnail, label: 'Image',
                                                help: "#{t('help.file_field', file_type: 'PNG, JPG', file_size: number_to_human_size(Event::MAX_FILE_SIZE))}<br />Dimensions: 1500x1500px, maintain a 150px gap on the left and right for the safe zone to display correctly on most devices".html_safe,
                                                data: { toggle: 'tooltip', placement: 'bottom', html: true,  title: image_tag('safe_zone.png').html_safe }

- case event_form.object.class.to_s
- when 'Event::CabinEvent'
  = multiselect event_form, :cabin_ids, cabins_for_select_for_user(current_ability), model_name(Cabin, plural: true), 'event_cabin_ids'
- when 'Event::CampEvent'
  = multiselect event_form, :camp_ids, camps_for_select_for_user(current_ability), model_name(Camp, plural: true), 'event_camp_ids'

= event_form.form_group label: { text: 'Visible in app' }, help: 'Show/hide this event from the app' do
  = event_form.check_box :active

app/views/admin/events/_national.html.haml
%ul.list-unstyled.mb-0
  %li
    %strong National

app/views/admin/events/_stream.html.haml
%ul.list-unstyled
  %li
    %strong Url:
    %br
    %span{ id: "stream-url-#{event.id}" } #{event.stream.input_url}
    %a.copy-to-clipboard{ href: '#', data: { target: "#stream-url-#{event.id}" } } #{icon('clipboard')}

  %li
    %strong Key:
    %br
    %span{ id: "stream-key-#{event.id}" } #{event.stream.key}
    %a.copy-to-clipboard{ href: '#', data: { target: "#stream-key-#{event.id}" } } #{icon('clipboard')}

  %li
    %strong Status:
    %br
    #{event.stream.channel.state}

app/views/admin/events/edit.html.haml
- title_bar "Edit #{@event.name}" do
  = delete_button(event_path(@event, event_type: params[:event_type]), text: "Delete #{@event.name}", remote: false, disabled: !@event.can_be_deleted?)

= bootstrap_form_with model: @event, url: event_path(@event, event_type: params[:event_type]), scope: :event do |event_form|
  = render 'form', event_form: event_form

  = event_form.form_group do
    = event_form.submit update_button_label(@event.class), class: 'btn btn-success'

app/views/admin/events/index.html.haml
- title_bar "#{model_name(@new_event.class)} (#{@showing_past ? 'Past' : 'Current'})" do
  - if can? :new, @new_event
    = new_button(new_button_label(@new_event.class), new_event_path(event_type: params[:event_type]))

  - if @showing_past
    = action_button(icon('list'), "Current #{model_name(@new_event.class, plural: true)}", events_path(event_type: params[:event_type]))
  - else
    = action_button(icon('list'), "Past #{model_name(@new_event.class, plural: true)}", events_path(event_type: params[:event_type], past: true))

.card.mb-3
  .card-body
    .row.align-items-center
      .col-12.col-md-2
        %strong.text-nowrap{ data: { toggle: 'tooltip', placement: 'bottom', title: 'The number of concurrent streams currently available' } }
          Active Streams:
      .col-12.col-md-9
        .progress
          .progress-bar{ style: "width: #{(@tenant.streams.count / @tenant.max_streams) * 100 rescue 0}%;" }
      .col-12.col-md-1.text-nowrap
        = "#{@tenant.streams.count}/#{@tenant.max_streams}"

    .row.align-items-center
      .col-12.col-md-2
        %strong.text-nowrap{ data: { toggle: 'tooltip', placement: 'bottom', title: 'The number of hours streaming used this month' } }
          Hours Streamed:
      .col-12.col-md-9
        .progress
          .progress-bar{ style: "width: #{@tenant.max_stream_hours_percentage}%;", class: (@tenant.max_stream_hours_percentage > 90 ? 'bg-danger' : '') }
      .col-12.col-md-1.text-nowrap
        = "#{@tenant.max_stream_hours_label}"

%p= page_entries_info @events, entry_name: "#{@showing_past ? 'past' : ''} #{entry_name_label(@new_event.class)}"

= paginate @events

.card.table-responsive
  %table.table.table-striped.table-borderless.mb-0
    %thead
      %tr
        %th Name
        %th Time
        %th Details
        %th Owner
        %th= @showing_past ? 'Status' : 'Stream'
        %th.actions Action

    %tbody
      - @events.each do |event|
        %tr{ id: dom_id(event), class: ('disabled' unless event.active?) }
          %td= event.name
          %td
            %ul.list-unstyled
              %li
                %strong= event.started_at ? 'Started:' : 'Starts:'
                = formatted_date(event.started_at || event.starts_at, default: '')
              %li
                %strong= event.ended_at? ? 'Ended:' : 'Ends:'
                = formatted_date(event.ended_at || event.ends_at, default: '')

          %td= render event.kind.downcase, event: event
          %td= event.admin&.full_name || 'Admin Deleted'
          %td
            - if @showing_past
              = event.active? ? 'Visible' : 'Hidden'
            - else
              = render 'stream', event: event if event.stream

          %td.actions
            - if event.closed?
              = link_to "#{icon('play-circle')} Start Stream".html_safe, start_event_path(event, event_type: params[:event_type]), method: :put, class: 'btn btn-sm btn-success', data: { disable_with: 'Starting...' }

            - if event.started?
              = link_to "#{icon('unlock')} Open".html_safe, open_event_path(event, event_type: params[:event_type]), method: :put, class: 'btn btn-sm btn-success', data: { disable_with: 'Opening...' }

            - if event.started? || event.open?
              = link_to "#{icon('stop-circle')} Stop & Close Stream".html_safe, stop_event_path(event, event_type: params[:event_type]), method: :put, class: 'btn btn-sm btn-danger', data: { disable_with: 'Stopping...' }

            .dropdown
              %button.btn.btn-sm.btn-info.dropdown-bs-toggle{ data: { toggle: 'dropdown' }, type: 'button' }
                = "#{icon('smartphone')} Send Notification".html_safe

              .dropdown-menu
                - decorated_event = EventDecorator.decorate(event)

                - ['starting', 'reminder'].each do |context|
                  - body = decorated_event.send("push_notification_body_#{context}")

                  = link_to context.humanize, event_push_notifications_path(event, event_type: params[:event_type], event_push_notification: { title: decorated_event.push_notification_title, body: body }),
                                              data: { confirm: "Are you sure you wish to send the notification:\n#{body}" },
                                              method: :post,
                                              class: 'dropdown-item'

                = link_to 'Custom', new_event_push_notification_path(event, event_type: params[:event_type]), class: 'dropdown-item'


            = edit_button(edit_event_path(event, event_type: params[:event_type]),'Edit')

= paginate @events

app/views/admin/events/new.html.haml
- title_bar new_button_label(@event.class)

= bootstrap_form_with model: @event, url: events_path(event_type: params[:event_type]), local: true, scope: :event do |event_form|
  = render 'form', event_form: event_form

  = event_form.form_group do
    = event_form.submit create_button_label(@event.class), class: 'btn btn-success'