config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'admin/home#index'

  resources :passwords, except: %i[show] do
    collection do
      get :unrecognised
      get :updated
    end
  end

  scope module: :admin, path: :admin do
    root to: 'home#index', as: :admin_root

    # Camp Management
    resources :camp_locations do
      resources :children, only: %i[index]
      resources :seasons, except: %i[show]
    end

    resources :welcome_videos, except: %i[show]

    resources :seasons, only: [] do
      resources :camps, except: %i[show]
    end

    resources :camps, only: [] do
      resources :attendances, module: :camps
      resources :cabins
      resources :media_items, except: %i[show]

      resources :imports, module: :camps, only: %i[new create show] do
        get :template_csv, on: :collection
      end
    end

    # Admin Settings
    resources :admins, except: %i[show]

    resources :children, except: %i[show]

    resources :color_themes, except: %i[show]

    resources :conversations, only: %i[index show]

    namespace :users do
      resources :sessions, only: %i[create destroy]
      resource :merge, only: %i[new create]
    end

    # Content Management
    resources :camper_questions, except: %i[new create show]

    scope ':event_type', constraints: { event_type: /national|camp|cabin/ }, defaults: { event_type: 'national' } do
      resources :events, except: %i[show] do
        member do
          put :start
          put :open
          put :stop
        end

        resources :push_notifications, module: :events, only: %i[new create]
      end
    end

    resources :media_items, except: %i[show]

    resources :themes

    resources :quiz_questions, only: %i[edit update destroy]

    resources :settings, only: %i[index edit update]

    resources :streams, except: %i[show] do
      member do
        put :stop
      end
    end

    resources :tenants, except: %i[show] do
      get :switch, on: :member
      get :reset, on: :collection
    end

    resources :users, only: %i[] do
      resources :attendances, module: :users, only: %i[index destroy]
      resources :scores, module: :users, only: %i[index]
    end

    resources :comet_chat_reviews
  end

  namespace :api do
    namespace :v1 do
      resource :version, controller: :version

      namespace :users do
        resource :sessions, only: %i[show destroy]
      end
    end

    namespace :v2 do
      # Camp Endpoints
      resources :attendances, param: :code, only: %i[show create]
      resources :camp_locations, only: %i[] do
        resources :camps, only: %i[index]
      end

      # Content Endpoints
      resource :contact, only: %i[create]
      resources :camper_questions, only: %i[index create] do
        get :unread, on: :collection
      end
      resources :events, only: %i[index show]
      resources :media_items, only: %i[index]
      resources :themes, only: %i[index] do
        resources :quiz_questions, only: %i[index]
      end
      resources :scores, only: %i[index create]

      # User Management Endpoints
      resource :user, only: %i[show update]

      namespace :admin do
        resources :groups, only: %i[create]
        resources :camps, only: %i[show] do
          resources :cabins, only: %i[index]
        end

        resources :events, only: %i[create update destroy] do
          resources :push_notifications, module: :events, only: %i[create]
        end

        resources :seasons, only: %i[index]
        resources :streams, only: %i[index]
      end

      namespace :authentications do
        resource :sessions, only: %i[create show destroy]
        resources :passwords, param: :reset_token, only: %i[create show update]
      end

      resources :authentications, only: %i[create] do
        collection do
          get :check_username
        end
      end

      resources :users, param: :chat_uid, only: [] do
        resources :messages, only: %i[destroy]
      end

      namespace :users do
        resource :device_token, only: %i[create]
        resources :conversations, only: %i[index]
        resources :reachable_users, only: %i[index]
      end

      resources :settings, only: :index
    end
  end

  # Nice login/logout routes
  get 'login'    => 'admin/users/sessions#new',      as: :login
  get 'logout'   => 'admin/users/sessions#destroy',  as: :logout
end

app/views/shared/_attachment_file_field.html.haml
= f.file_field attribute, options.merge(placeholder: (attachment.filename if attachment&.attached?))
- if f.object&.persisted? && attachment&.attached?
  = link_to rails_blob_path(attachment, disposition: 'attachment'), class: 'd-inline-block mb-3' do
    %small Current #{attribute.to_s.titleize}

app/views/shared/_cabin_admin_nav.html.haml
= sidebar_sublist('Events') do
  = nav_link Cabin, events_path(event_type: 'cabin'), 'cast'

= render 'shared/training_manual'

app/views/shared/_camp_admin_nav.html.haml
= sidebar_sublist('User Management') do
  = nav_link CampLocation, camp_locations_path, 'compass'
  = nav_link User::Child, camp_location_children_path(current_user.camp_location), 'users'

= sidebar_sublist('Content') do
  = nav_link CamperQuestion, camper_questions_path, 'help-circle'
  = nav_link Theme, themes_path, 'check-square'

= sidebar_sublist('Events') do
  = nav_link Event::CampEvent, events_path(event_type: 'camp'), 'cast'
  = nav_link Event::CabinEvent, events_path(event_type: 'cabin'), 'cast'

= sidebar_sublist('Admin Settings') do
  = nav_link User::Admin, admins_path, 'users'
  = nav_link 'Conversation Review', conversations_path, 'message-square'

= render 'shared/training_manual'

app/views/shared/_flash.html.haml
.flash-messages.w-100
  - if flash.keys.any?
    .inner
      - [:notice, :error, :message].each do |name|
        - if flash[name]
          - case name
          - when :notice
            .alert.alert-success
              %button.close{'data-dismiss' => 'alert'} ×
              %strong Success!
              = flash[name].html_safe
          - when :error
            .alert.alert-danger
              %button.close{'data-dismiss' => 'alert'} ×
              %strong Error!
              = flash[name].html_safe
          - when :message
            .alert.alert-info
              %button.close{'data-dismiss' => 'alert'} ×
              %strong Info!
              = flash[name].html_safe

app/views/shared/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.shadow.navbar-ohc.flex-lg-row.align-items-lg-center
  = link_to root_path, class: 'navbar-brand col-lg-2' do
    %span= current_tenant ? current_tenant.name : 'Faith Spark'



  - if logged_in?
    %ul.navbar-nav.navbar-submenu.d-lg-none
      %li.nav-item.text-nowrap
        - if current_user.tenant == current_tenant
          = link_to 'Profile', edit_admin_path(current_user), class: 'nav-link'
      %li.nav-item.text-nowrap
        = link_to 'Sign out', logout_path, class: 'nav-link'

    %button.navbar-toggler{ data: { toggle: 'collapse', target: '.header-content' } }
      %span.navbar-toggler-icon

    %nav.breadcrumbs.w-100.d-flex.justify-content-between{ aria: { label: 'breadcrumb' } }
      %ol.breadcrumb.m-1
        - if @breadcrumbs.present?
          - @breadcrumbs.each do |crumb|
            %li.breadcrumb-item
              - if crumb.second
                = link_to crumb.first, crumb.second
              - else
                = crumb.first

      %ul.navbar-nav.m-2
        -#  Remove clock from nav bar - DE Apr 18,2023
        -#  %li.text-nowrap
        -#  #current-time.nav-link.disabled= l(Time.zone.now)

        - if current_user.tenant == current_tenant
          %li.d-none.d-lg-flex= link_to 'Profile', edit_admin_path(current_user), class: 'nav-link'

        %li.d-none.d-lg-flex= link_to 'Sign out', logout_path, class: 'nav-link'

app/views/shared/_more_button.html.haml
.dropdown
  %button.btn.btn-light.btn-sm{ "data-bs-toggle" => 'dropdown', type: 'button' }
    = icon(icon_name)
  .dropdown-menu.dropdown-menu-right
    = items

app/views/shared/_multiselect.html.haml
.multiselect
  .hidden
    = builder.select attribute, values, { label: label }, multiple: true, id: id

  = builder.form_group label: { text: label } do
    %ul.list-group{ data: { target: "##{id}" }, class: (builder.object.errors[attribute].any? ? 'is-invalid' : '') }
      - values.each do |label, id|
        %li.list-group-item{ data: { value: id }, class: (builder.object.send(attribute).include?(id) ? 'active' : '') }
          = builder.object.send(attribute).include?(id) ? icon('check-square') : icon('square')
          = label

    - if builder.object.errors[attribute].any?
      %ul.invalid-feedback
        - builder.object.errors[attribute].each do |error|
          %li= error

app/views/shared/_search_form.html.haml
= bootstrap_form_with url: search_path, method: :get, local: true do |f|
  = f.form_group do
    = f.label :search_term, 'Search'
    = f.text_field :search_term, value: params[:search_term], wrapper: false
    %small= message

  = f.form_group do
    = f.submit 'Search'

app/views/shared/_sidebar.html.haml
%nav.col-lg-2.collapse.d-lg-block.bg-light.sidebar.header-content
  .sidebar-sticky
    = render "shared/#{current_user.role}_nav"

app/views/shared/_super_admin_nav.html.haml
= sidebar_sublist('User Management') do
  = nav_link CampLocation, camp_locations_path, 'compass'
  = nav_link User::Child, children_path, 'users'

= sidebar_sublist('Content') do
  = nav_link CamperQuestion, camper_questions_path, 'help-circle'
  = nav_link Theme, themes_path, 'check-square'

= sidebar_sublist('Events') do
  = nav_link Event::NationalEvent, events_path, 'cast'
  = nav_link Event::CampEvent, events_path(event_type: 'camp'), 'cast'
  = nav_link Event::CabinEvent, events_path(event_type: 'cabin'), 'cast'

= sidebar_sublist('Gallery') do
  = nav_link MediaItem::NationalMediaItem, media_items_path, 'image'

= sidebar_sublist('Admin Settings') do
  = nav_link Setting, edit_tenant_path(current_tenant), 'settings'
  = nav_link User::Admin, admins_path, 'users'
  = nav_link WelcomeVideo, welcome_videos_path, 'video'
  = nav_link 'Conversation Review', conversations_path, 'message-square'

= render 'shared/training_manual'

app/views/shared/_training_manual.html.haml
- if help_manual_url = Setting.find_by(name: 'Training Manual URL')&.value
  = sidebar_sublist('Help') do
    = nav_link 'Training Manual', help_manual_url, 'help-circle', target: '_blank'

app/views/shared/_welcome_or_custom_video.html.haml
= f.form_group :video, label: { text: 'Video' } do
  = f.select :welcome_video_id, WelcomeVideo.active.accessible_by(current_ability).pluck(:name, :id), { include_blank: 'Custom Video', hide_label: true }, id: 'welcome-video-select'

  .custom
    = attachment_file_field(f, :video, help: t('help.file_field', file_type: 'MP4', file_size: number_to_human_size(f.object.class::MAX_FILE_SIZE)).html_safe, hide_label: true)

:javascript
  document.addEventListener('turbolinks:load', () => {
    const $customWrapper = $('.custom');
    const $customSelect = $('#welcome-video-select');

    function toggleCustomFileField() {
      $customWrapper.toggle(!$customSelect.val());
    }

    toggleCustomFileField();

    $customSelect.on('change', function() {
      toggleCustomFileField();
    });
  });

app/views/shared/destroy.js.erb
$('#<%= id %>').fadeOut();

app/views/shared/refresh_flash.js.haml
$('.flash-messages').replaceWith('#{ j render 'shared/flash.html.haml' }');