config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'admin/home#index'

  resources :passwords, except: %i[show] do
    collection do
      get :unrecognised
      get :updated
    end
  end

  scope module: :admin, path: :admin do
    root to: 'home#index', as: :admin_root

    # Camp Management
    resources :camp_locations do
      resources :children, only: %i[index]
      resources :seasons, except: %i[show]
    end

    resources :welcome_videos, except: %i[show]

    resources :seasons, only: [] do
      resources :camps, except: %i[show]
    end

    resources :camps, only: [] do
      resources :attendances, module: :camps
      resources :cabins
      resources :media_items, except: %i[show]

      resources :imports, module: :camps, only: %i[new create show] do
        get :template_csv, on: :collection
      end
    end

    # Admin Settings
    resources :admins, except: %i[show]

    resources :children, except: %i[show]

    resources :color_themes, except: %i[show]

    resources :conversations, only: %i[index show]

    namespace :users do
      resources :sessions, only: %i[create destroy]
      resource :merge, only: %i[new create]
    end

    # Content Management
    resources :camper_questions, except: %i[new create show]

    scope ':event_type', constraints: { event_type: /national|camp|cabin/ }, defaults: { event_type: 'national' } do
      resources :events, except: %i[show] do
        member do
          put :start
          put :open
          put :stop
        end

        resources :push_notifications, module: :events, only: %i[new create]
      end
    end

    resources :media_items, except: %i[show]

    resources :themes

    resources :quiz_questions, only: %i[edit update destroy]

    resources :settings, only: %i[index edit update]

    resources :streams, except: %i[show] do
      member do
        put :stop
      end
    end

    resources :tenants, except: %i[show] do
      get :switch, on: :member
      get :reset, on: :collection
    end

    resources :users, only: %i[] do
      resources :attendances, module: :users, only: %i[index destroy]
      resources :scores, module: :users, only: %i[index]
    end

    resources :comet_chat_reviews
  end

  namespace :api do
    namespace :v1 do
      resource :version, controller: :version

      namespace :users do
        resource :sessions, only: %i[show destroy]
      end
    end

    namespace :v2 do
      # Camp Endpoints
      resources :attendances, param: :code, only: %i[show create]
      resources :camp_locations, only: %i[] do
        resources :camps, only: %i[index]
      end

      # Content Endpoints
      resource :contact, only: %i[create]
      resources :camper_questions, only: %i[index create] do
        get :unread, on: :collection
      end
      resources :events, only: %i[index show]
      resources :media_items, only: %i[index]
      resources :themes, only: %i[index] do
        resources :quiz_questions, only: %i[index]
      end
      resources :scores, only: %i[index create]

      # User Management Endpoints
      resource :user, only: %i[show update]

      namespace :admin do
        resources :groups, only: %i[create]
        resources :camps, only: %i[show] do
          resources :cabins, only: %i[index]
        end

        resources :events, only: %i[create update destroy] do
          resources :push_notifications, module: :events, only: %i[create]
        end

        resources :seasons, only: %i[index]
        resources :streams, only: %i[index]
      end

      namespace :authentications do
        resource :sessions, only: %i[create show destroy]
        resources :passwords, param: :reset_token, only: %i[create show update]
      end

      resources :authentications, only: %i[create] do
        collection do
          get :check_username
        end
      end

      resources :users, param: :chat_uid, only: [] do
        resources :messages, only: %i[destroy]
      end

      namespace :users do
        resource :device_token, only: %i[create]
        resources :conversations, only: %i[index]
        resources :reachable_users, only: %i[index]
      end

      resources :settings, only: :index
    end
  end

  # Nice login/logout routes
  get 'login'    => 'admin/users/sessions#new',      as: :login
  get 'logout'   => 'admin/users/sessions#destroy',  as: :logout
end

app/models/camp_location.rb
# frozen_string_literal: true

class CampLocation < ApplicationRecord
  include TenantResource

  has_many :admins, dependent: :restrict_with_error, class_name: 'User::Admin'
  has_many :themes, dependent: :destroy

  has_many :seasons, dependent: :destroy
  has_many :camps, through: :seasons
  has_many :children, through: :seasons
  has_many :users, through: :seasons, dependent: :restrict_with_error

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :notification_email, email: true

  def all_camps
    Camp.where(season_id: season_ids)
  end

  def all_cabins
    Cabin.where(camp_id: all_camps.ids)
  end

  def can_be_deleted?
    users.empty?
  end
end

app/controllers/admin/camp_locations_controller.rb
# frozen_string_literal: true

module Admin
  class CampLocationsController < ApplicationController
    def index
      authorize! :index, CampLocation

      @search = CampLocation.ransack(params[:q])
      @search.sorts = 'name asc' if @search.sorts.empty?

      @camp_locations = @search.result
                               .accessible_by(current_ability, :index)
                               .page(params[:page])
    end

    def new
      @camp_location = CampLocation.new(tenant_params)

      authorize! :create, @camp_location
    end

    def create
      @camp_location = CampLocation.new(allowed_params_with_tenant)

      authorize! :create, @camp_location

      if @camp_location.save
        redirect_to camp_location_path(@camp_location), flash: { notice: t('flash.actions.create.notice', resource_name: resource_name) }
      else
        render :new
      end
    end

    def show
      @camp_location = fetch_camp_location

      authorize! :read, @camp_location

      if @camp_location.size == 1
        "hello"
        redirect_to camp_location_path
      else

        @search = @camp_location.seasons
                                .accessible_by(current_ability)
                                .ransack(params[:q])

        @search.sorts = 'name asc' if @search.sorts.empty?

        @seasons = @search.result
                          .page(params[:page])
      end
    end

    def edit
      @camp_location = fetch_camp_location

      authorize! :update, @camp_location
    end

    def update
      @camp_location = fetch_camp_location

      authorize! :update, @camp_location

      if @camp_location.update(allowed_params_with_tenant)
        redirect_to camp_locations_path, flash: { notice: t('flash.actions.update.notice', resource_name: resource_name) }
      else
        render :edit
      end
    end

    def destroy
      @camp_location = fetch_camp_location

      authorize! :destroy, @camp_location

      if @camp_location.destroy
        flash[:notice] = t('flash.actions.destroy.notice', resource_name: resource_name)
      else
        flash[:error] = t('flash.actions.destroy.error', resource_name: resource_name)
      end

      redirect_to camp_locations_path
    end

    private

    def fetch_camp_location
      @fetch_camp_location ||= CampLocation.find(params[:id])
    end

    def allowed_params
      params.require(:camp_location).permit(:name, :notification_email)
    end

    def generate_breadcrumbs
      add_breadcrumb(fetch_camp_location.name) if params[:id].present?
    end

    def resource_name
      model_name(CampLocation)
    end
  end
end

app/views/admin/camp_locations/_form.html.haml
= render 'shared/form_base_errors', f: f

= f.text_field :name

= f.text_field :notification_email, help: t('help.camp_locations.notification_email', model: model_name(CamperQuestion, plural: true)).html_safe

app/views/admin/camp_locations/edit.html.haml
- title_bar "Edit #{@camp_location.name}" do
  = delete_button(@camp_location, text: "Delete #{@camp_location.name}", remote: false, disabled: !@camp_location.can_be_deleted?)

= bootstrap_form_with model: @camp_location, url: camp_location_path(@camp_location) do |f|
  = render 'form', f: f

  = f.form_group do
    = f.submit update_button_label(CampLocation), class: 'btn btn-success'

app/views/admin/camp_locations/index.html.haml
- title_bar model_name(CampLocation, plural: true) do
  = new_button(new_button_label(CampLocation), new_camp_location_path)

%p= page_entries_info @camp_locations, entry_name: entry_name_label(CampLocation)

-# if @camp_locations.size == 1
  -#= render 'show', camp_location_path(@camp_locations[0])

.row.mb-3.align-items-center
  .col-12.col-md-8
    Sort:
    = sort_link(@search, :name)
    |
    = sort_link(@search, :created_at, 'Created')

  .col-12.col-md-4
    = search_form_for @search, url: camp_locations_path do |s|
      .input-group
        = s.search_field :name_cont, placeholder: 'Search (Name)', class: 'form-control form-control-sm'
        .input-group-append
          = s.submit 'Search', class: 'btn btn-sm btn-secondary'

= paginate @camp_locations

.row.row-cols-1.row-cols-md-5.g-1
  - @camp_locations.each do |camp_location|
    .card.text-bg-info.h-100.m-1{ id: dom_id(camp_location), data: { href: camp_location_path(camp_location) } }
      .card-body
        .row
          .col.text-truncate
            = camp_location.name
          .col.text-end
            = edit_button( edit_camp_location_path(camp_location), '')

- if @camp_locations.none?
  .card.mb-3
    .card-body.text-center.disabled= no_items_label(CampLocation)

= paginate @camp_locations

app/views/admin/camp_locations/new.html.haml
- title_bar new_button_label(CampLocation)

= bootstrap_form_with model: @camp_location, url: camp_locations_path, local: true do |f|
  = render 'form', f: f

  = f.form_group do
    = f.submit create_button_label(CampLocation), class: 'btn btn-success'

app/views/admin/camp_locations/show.html.haml
- title_bar @camp_location.name do
  = new_button(new_button_label(Season), new_camp_location_season_path(@camp_location))

%p= page_entries_info @seasons, entry_name: entry_name_label(Season)

= paginate @seasons

.row.mb-3.align-items-center
  .col-12.col-md-8
    Sort:
    = sort_link(@search, :name)
    |
    = sort_link(@search, :created_at, 'Created')

  .col-12.col-md-4
    = search_form_for @search, url: camp_location_path(@camp_location) do |s|
      .input-group
        = s.search_field :name_cont, placeholder: "Search (#{model_name(Season)} Name)", class: 'form-control form-control-sm'
        .input-group-append
          = s.submit 'Search', class: 'btn btn-sm btn-secondary'

- @seasons.each do |season|
  .card.mb-3
    .card-header
      .row
        .col-10
          %strong= "#{model_name(Season)}:"
          = season.name
        .col-2.text-end
          = link_to "#{icon('edit')} Edit".html_safe, edit_camp_location_season_path(@camp_location, season), class: 'btn btn-info btn-sm'            

    .card-body
      - season.camps.accessible_by(current_ability).each do |camp|
        .card.mb-1.bg-light
          .card-header
            .row
              .col-8
                %strong= "#{model_name(Camp)}:"
                = camp.name
                = link_to "#{icon('edit')} Edit".html_safe, edit_season_camp_path(camp.season, camp), class: 'btn btn-info btn-sm'
              .col-4
                %p.text-end
                = link_to "#{icon('image')} #{model_name(MediaItem::CampMediaItem, plural: true)}".html_safe, camp_media_items_path(camp), class: 'btn btn-info btn-sm'
                = link_to "#{icon('upload')} Import".html_safe, new_camp_import_path(camp), class: 'btn btn-info btn-sm'
                = link_to "#{icon('download')} Export".html_safe, camp_attendances_path(camp, format: :csv), class: 'btn btn-info btn-sm'
                = new_button new_button_label(Cabin), new_camp_cabin_path(camp)


          .card-body
            
            .row.mb-2.row-cols-auto          
              - camp.cabins.accessible_by(current_ability).each do |cabin|
                .col.lg-4.col-sm-3.col-md-2
                  .card.text-bg-info.mb-1{DATA: {href: camp_cabin_path(cabin.camp, cabin) } }
                    .card-body
                      .row 
                        .col-9                      
                          %p.text.font-size-lg
                            %strong= cabin.name
                        .col-2.col-md-1.me1.text-end
                          = link_to "#{icon('edit')}".html_safe, edit_camp_cabin_path(camp, cabin), class: 'btn btn-info btn-sm'
                        %p.text.font-size-sm 
                          %strong= cabin.gender 
                          %strong= "#{model_name(User::Child, plural: true)}:"
                          = cabin.children.count
                        
                          



      .card.mb-3.bg-light
        .card-body.text-center= new_button new_button_label(Camp), new_season_camp_path(season)

- if @seasons.none?
  .card.mb-3
    .card-body.text-center.disabled= no_items_label(Season)

= paginate @seasons