config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'admin/home#index'

  resources :passwords, except: %i[show] do
    collection do
      get :unrecognised
      get :updated
    end
  end

  scope module: :admin, path: :admin do
    root to: 'home#index', as: :admin_root

    # Camp Management
    resources :camp_locations do
      resources :children, only: %i[index]
      resources :seasons, except: %i[show]
    end

    resources :welcome_videos, except: %i[show]

    resources :seasons, only: [] do
      resources :camps, except: %i[show]
    end

    resources :camps, only: [] do
      resources :attendances, module: :camps
      resources :cabins
      resources :media_items, except: %i[show]

      resources :imports, module: :camps, only: %i[new create show] do
        get :template_csv, on: :collection
      end
    end

    # Admin Settings
    resources :admins, except: %i[show]

    resources :children, except: %i[show]

    resources :color_themes, except: %i[show]

    resources :conversations, only: %i[index show]

    namespace :users do
      resources :sessions, only: %i[create destroy]
      resource :merge, only: %i[new create]
    end

    # Content Management
    resources :camper_questions, except: %i[new create show]

    scope ':event_type', constraints: { event_type: /national|camp|cabin/ }, defaults: { event_type: 'national' } do
      resources :events, except: %i[show] do
        member do
          put :start
          put :open
          put :stop
        end

        resources :push_notifications, module: :events, only: %i[new create]
      end
    end

    resources :media_items, except: %i[show]

    resources :themes

    resources :quiz_questions, only: %i[edit update destroy]

    resources :settings, only: %i[index edit update]

    resources :streams, except: %i[show] do
      member do
        put :stop
      end
    end

    resources :tenants, except: %i[show] do
      get :switch, on: :member
      get :reset, on: :collection
    end

    resources :users, only: %i[] do
      resources :attendances, module: :users, only: %i[index destroy]
      resources :scores, module: :users, only: %i[index]
    end

    resources :comet_chat_reviews
  end

  namespace :api do
    namespace :v1 do
      resource :version, controller: :version

      namespace :users do
        resource :sessions, only: %i[show destroy]
      end
    end

    namespace :v2 do
      # Camp Endpoints
      resources :attendances, param: :code, only: %i[show create]
      resources :camp_locations, only: %i[] do
        resources :camps, only: %i[index]
      end

      # Content Endpoints
      resource :contact, only: %i[create]
      resources :camper_questions, only: %i[index create] do
        get :unread, on: :collection
      end
      resources :events, only: %i[index show]
      resources :media_items, only: %i[index]
      resources :themes, only: %i[index] do
        resources :quiz_questions, only: %i[index]
      end
      resources :scores, only: %i[index create]

      # User Management Endpoints
      resource :user, only: %i[show update]

      namespace :admin do
        resources :groups, only: %i[create]
        resources :camps, only: %i[show] do
          resources :cabins, only: %i[index]
        end

        resources :events, only: %i[create update destroy] do
          resources :push_notifications, module: :events, only: %i[create]
        end

        resources :seasons, only: %i[index]
        resources :streams, only: %i[index]
      end

      namespace :authentications do
        resource :sessions, only: %i[create show destroy]
        resources :passwords, param: :reset_token, only: %i[create show update]
      end

      resources :authentications, only: %i[create] do
        collection do
          get :check_username
        end
      end

      resources :users, param: :chat_uid, only: [] do
        resources :messages, only: %i[destroy]
      end

      namespace :users do
        resource :device_token, only: %i[create]
        resources :conversations, only: %i[index]
        resources :reachable_users, only: %i[index]
      end

      resources :settings, only: :index
    end
  end

  # Nice login/logout routes
  get 'login'    => 'admin/users/sessions#new',      as: :login
  get 'logout'   => 'admin/users/sessions#destroy',  as: :logout
end

app/models/media_item.rb
# frozen_string_literal: true

class MediaItem < ApplicationRecord
  MAX_FILE_SIZE = 300.megabytes

  include TenantResource

  belongs_to :camp, optional: true
  belongs_to :user

  scope :active, -> { where(active: true) }

  has_one_attached :attachment

  validates :attachment, attached: true,
                         content_type: %w[image/png image/jpg image/jpeg video/mp4],
                         size: { less_than: MAX_FILE_SIZE }
end

app/models/media_item/camp_media_item.rb
# frozen_string_literal: true

class MediaItem::CampMediaItem < MediaItem
  belongs_to :camp
end

app/models/media_item/national_media_item.rb
# frozen_string_literal: true

class MediaItem::NationalMediaItem < MediaItem
end

app/controllers/admin/media_items_controller.rb
# frozen_string_literal: true

module Admin
  class MediaItemsController < ApplicationController
    def index
      authorize! :index, klass

      @camp = fetch_camp

      @search = scope.ransack(params[:q])
      @search.sorts = ['active desc', 'created_at asc'] if @search.sorts.empty?

      @media_items = @search.result
                            .accessible_by(current_ability, :index)
                            .includes(:user)
                            .with_attached_attachment
                            .page(params[:page])

      @new_media_item = klass.new
    end

    def new
      @media_item = scope.new(tenant_params)

      authorize! :create, @media_item
    end

    def create
      @media_item = scope.new(attributes_from_params)

      authorize! :create, @media_item

      respond_to do |format|
        if @media_item.save
          format.js { head :created }
          format.html do
            redirect_to redirect_path, flash: { notice: t('flash.actions.create.notice', resource_name: resource_name) }
          end
        else
          format.js { render status: 400 }
          format.html { render :new }
        end
      end
    end

    def edit
      @media_item = fetch_media_item

      authorize! :update, @media_item
    end

    def update
      @media_item = fetch_media_item

      authorize! :update, @media_item

      if @media_item.update(attributes_from_params)
        redirect_to redirect_path, flash: { notice: t('flash.actions.update.notice', resource_name: resource_name) }
      else
        render :edit
      end
    end

    def destroy
      @media_item = fetch_media_item

      authorize! :destroy, @media_item

      if @media_item.destroy
        flash[:notice] = t('flash.actions.destroy.notice', resource_name: resource_name)
      else
        flash[:error] = t('flash.actions.destroy.error', resource_name: resource_name)
      end

      redirect_to redirect_path
    end

    private

    def allowed_params
      params.require(:media_item).permit(:active, :attachment)
    end

    def fetch_camp
      return nil if params[:camp_id].blank?

      @fetch_camp || Camp.accessible_by(current_ability)
                         .find(params[:camp_id])
    end

    def fetch_media_item
      @fetch_media_item ||= klass.find(params[:id])
    end

    def attributes_from_params
      allowed_params_with_tenant.tap do |attributes|
        attributes[:user_id] = current_user.id
      end
    end

    def redirect_path
      fetch_camp ? camp_media_items_path(fetch_camp) : media_items_path
    end

    def scope
      params[:camp_id].present? ? fetch_camp.media_items : klass
    end

    def klass
      params[:camp_id].present? ? MediaItem::CampMediaItem : MediaItem::NationalMediaItem
    end

    def generate_breadcrumbs
      if fetch_camp
        add_breadcrumb(fetch_camp.season.camp_location.name, camp_location_path(fetch_camp.season.camp_location))
        add_breadcrumb(fetch_camp.season.name)
        add_breadcrumb(fetch_camp.name)
        add_breadcrumb('Gallery', camp_media_items_path(fetch_camp))
      else
        add_breadcrumb('Gallery', media_items_path)
      end

      add_breadcrumb(fetch_media_item.attachment.filename) if params[:id].present?
    end

    def resource_name
      model_name(MediaItem)
    end
  end
end

app/controllers/api/v2/media_items_controller.rb
# frozen_string_literal: true

module API
  module V2
    class MediaItemsController < BaseController
      # == [GET] /api/v2/media_items.json
      # Retrieve an index of <MediaItem>s
      # ==== Returns
      # * 200 - success - returns an array of <MediaItem>
      def index
        media_items = MediaItem.accessible_by(current_ability)
                               .active

        render json: API::V2::MediaItemSerializer.new(media_items, serializer_params)
      end
    end
  end
end

app/views/admin/media_items/_form.html.haml
= render 'shared/form_base_errors', f: f

= attachment_file_field(f, :attachment, help: t('help.file_field', file_type: 'MP4, PNG, JPG', file_size: number_to_human_size(MediaItem::MAX_FILE_SIZE)).html_safe)

= f.form_group label: { text: 'Visible in app' }, help: 'Show/hide this item from the app' do
  = f.check_box :active

app/views/admin/media_items/create.js.haml
= @media_item.errors.to_a.to_sentence

app/views/admin/media_items/edit.html.haml
- path = @media_item.camp ? camp_media_item_path(@media_item.camp, @media_item) : media_item_path(@media_item)

- title_bar edit_button_label(MediaItem) do
  = delete_button(path, text: "Delete #{model_name(MediaItem)}")

= bootstrap_form_with model: @media_item, url: path, scope: :media_item do |f|
  = render 'form', f: f

  = f.form_group do
    = f.submit update_button_label(MediaItem), class: 'btn btn-success', data: { disable_with: 'Uploading...' }

app/views/admin/media_items/index.html.haml
- title_bar model_name(@new_media_item.class, plural: true) do
  = new_button(new_button_label(@new_media_item.class), @camp ? new_camp_media_item_path(@camp) : new_media_item_path)

%p= page_entries_info @media_items, entry_name: entry_name_label(@new_media_item.class)

= paginate @media_items

.card.table-responsive
  %table.table.table-striped.table-borderless.mb-0
    %thead
      %tr
        %th Thumbnail
        %th Uploaded By
        %th= sort_link(@search, :updated_at, text: 'Updated')
        %th= sort_link(@search, :active)
        %th.actions Action

    %tbody
      - @media_items.each do |media_item|
        %tr{ id: dom_id(media_item), class: ('disabled' unless media_item.active?) }
          %td
            .preview.img-thumbnail
              - if media_item.attachment.image?
                = image_tag(media_item.attachment.variant(resize: '50x50'), title: media_item.attachment.filename)
              - elsif media_item.attachment.previewable?
                = image_tag(media_item.attachment.preview(resize_to_limit: [50, 50]), title: media_item.attachment.filename)

          %td= media_item.user.full_name
          %td= formatted_date(media_item.updated_at, default: '')
          %td= media_item.active? ? 'Visible' : 'Hidden'
          %td.actions
            = edit_button(@camp ? edit_camp_media_item_path(media_item.camp, media_item) : edit_media_item_path(media_item),'')

  = paginate @media_items

app/views/admin/media_items/new.html.haml
- title_bar new_button_label(MediaItem)

= bootstrap_form_with model: @media_item, local: true, url: (@media_item.camp ? camp_media_items_path(@media_item.camp, format: 'js') : media_items_path(format: 'js')), id: 'new-media-item', scope: :media_item do |f|
  .fallback
    = render 'form', f: f

    = f.form_group do
      = f.submit create_button_label(MediaItem), class: 'btn btn-success', data: { disable_with: 'Uploading...' }

  .card.drop-area.mb-3
    .card-body.text-center.m-5
      = icon('upload-cloud')
      %br
      Drop files here to click to upload

  %p.form-text.text-muted= t('help.file_field', file_type: 'MP4, PNG, JPG', file_size: number_to_human_size(MediaItem::MAX_FILE_SIZE)).html_safe

#previews
  .card.mb-3
    .card-body
      .row.align-items-center
        .col-3
          .preview.img-thumbnail
            %img{ data: { 'dz-thumbnail': '' } }
        .col-3
          %strong Filename:
          %p.m-0.name{ data: { 'dz-name': '' } }
        .col-3
          %strong Size:
          %p.m-0.size{ data: { 'dz-size': '' } }
        .col-3
          %strong Progress:
          .progress.progress-striped.active{ aria: { valuemax: '100', valuemin: '0', valuenow: '0' }, role: 'progressbar'}
            .progress-bar.progress-bar-success{ data: { 'dz-uploadprogress': '' }, style: 'width: 0%;' }

          .error.text-danger{ data: { 'dz-errormessage': '' } }
          .success.d-none Complete

= link_to "#{icon('list')} Back To List".html_safe, @media_item.camp ? camp_media_items_path(@media_item.camp) : media_items_path, class: 'btn btn-primary'

:javascript
  document.addEventListener('turbolinks:load', () => {
    const previewNode = $('#previews');
    const previewTemplate = previewNode.html();

    previewNode.html('');

    const mediaDropZone = new Dropzone('#new-media-item', {
      paramName: 'media_item[attachment]',
      thumbnailHeight: 50,
      thumbnailWidth: 50,
      parallelUploads: 1,
      maxFilesize: #{MediaItem::MAX_FILE_SIZE / 1024 / 1024}, // In MB
      previewTemplate: previewTemplate,
      previewsContainer: "#previews",
      clickable: ".drop-area",
      acceptedFiles: 'image/png,image/jpg,image/jpeg,video/mp4',
      timeout: 1800000 // 30 Minutes
    });

    mediaDropZone.on('complete', function(file) {
      file.previewElement.querySelector('.progress').classList.add('d-none');
      file.previewElement.querySelector('.success').classList.remove('d-none');
    });
  });